### ISSUE TITLE
UDP CLIENT TypeError: 'str' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by ostronic** [edoardottt/black-hat-python3-code#6]
line 13, in <module>
    client.sendto(b"AAABBBCCC", (target_host,target_port))
TypeError: 'str' object cannot be interpreted as an integer

I also tried formatting no avail. Where can i be getting it wrong ??

**Comment by edoardottt** [comment]
It's difficult to provide some kind of assistance with just this information.

Please provide the python version, exact steps you took, the input and how you executed the command.

**Comment by ostronic** [comment]
Thanks i figured it out
